name: Handle Large File Changes

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  handle-large-changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.changed_files > 1000 || github.event.pull_request.deletions > 10000
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze large changes
        run: |
          echo "🔍 Analyzing large file changes..."
          
          # Get the diff stats
          git diff --stat HEAD~1
          
          # Count files changed
          CHANGED_FILES=$(git diff --name-only HEAD~1 | wc -l)
          DELETIONS=$(git diff --stat HEAD~1 | grep -o '[0-9]* deletions' | grep -o '[0-9]*' || echo "0")
          
          echo "📊 Changed files: $CHANGED_FILES"
          echo "🗑️ Deletions: $DELETIONS"
          
          # If this is mainly deletions of content files, approve automatically
          if [ "$DELETIONS" -gt 10000 ]; then
            echo "⚠️ Large number of deletions detected"
            
            # Check if deletions are mainly in content directories
            CONTENT_DELETIONS=$(git diff --name-only HEAD~1 --diff-filter=D | grep -E '^(files/|content/)' | wc -l || echo "0")
            
            if [ "$CONTENT_DELETIONS" -gt $(($CHANGED_FILES * 80 / 100)) ]; then
              echo "✅ Most deletions are content files - likely safe to proceed"
              echo "AUTO_APPROVE=true" >> $GITHUB_ENV
            else
              echo "⚠️ Deletions include non-content files - manual review needed"
              echo "AUTO_APPROVE=false" >> $GITHUB_ENV
            fi
          fi

      - name: Add helpful comment
        uses: actions/github-script@v7
        if: github.event.pull_request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const autoApprove = process.env.AUTO_APPROVE === 'true';
            
            const body = autoApprove 
              ? `## 🤖 Large Change Analysis - Auto-Approved ✅

                This PR contains a large number of file changes/deletions, but analysis shows:
                
                - ✅ Most changes appear to be content file deletions
                - ✅ Core project files are preserved
                - ✅ Safe to merge automatically
                
                **Recommendation:** This change appears safe and can be merged.`
              : `## 🤖 Large Change Analysis - Manual Review Needed ⚠️

                This PR contains a large number of file changes/deletions:
                
                - ⚠️ Changes include non-content files
                - ⚠️ Manual review recommended
                - ⚠️ Verify core functionality is preserved
                
                **Recommendation:** Please review carefully before merging.`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Auto-approve if safe
        uses: actions/github-script@v7
        if: env.AUTO_APPROVE == 'true' && github.event.pull_request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: '🤖 Auto-approved: Large changes appear to be safe content deletions.'
            });
